language: python
services: docker
env:
  - DOCKER_BUILDKIT=1
before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - ./build.sh
after_script:
  - docker images
